name             'fronend'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures fronend'
long_description 'Installs/Configures fronend'
version          '0.1.0'
depends 's3_file'
